Feature/fix tg webhooks controller
Ashab-al/telegram-bot_ashab pull request #13
Opened 2024-12-27 20:20 UTC by Ashab-al

2024-12-27 21:10 UTC, sov-87 requested changes

2024-12-27 21:10 UTC, sov-87 commented on app/interactors/tg/open_vacancy_interactor.rb
> +    return false if blacklist and blacklist.complaint_counter >= 2
2 вынести в константы

2024-12-27 21:10 UTC, sov-87 commented on app/interactors/tg/spam_vacancy_interactor.rb
> +    contact_information = vacancy.source == "tg_chat" ? vacancy.platform_id : vacancy.contact_information
tg_chat - в константы

2024-12-27 21:10 UTC, sov-87 commented on app/interactors/tg/spam_vacancy_interactor.rb
> +    if blacklist.complaint_counter >= 2
2 в константы. кстати, это то же самое число, что и в `app/interactors/tg/open_vacancy_interactor.rb`

Надо выносить в константу, которая находится в отдельном файле и видна им обоим.

2024-12-27 21:10 UTC, sov-87 commented on app/interactors/tg/spam_vacancy_interactor.rb
> +      bot.answer_callback_query "Эта вакансия была определена как нежелательная и добавлена в наш черный список. 🚫😕", show_alert: true
здесь переводы

2024-12-27 21:10 UTC, sov-87 commented on app/interactors/tg/total_vacancies_interactor.rb
> +      category_vacancies_count = vacancies_by_category[category.name] || 0
получается, у тебя есть неявная связь Category-Vacancy. Почему бы не сделать ее явной?

2024-12-28 23:03 UTC, Ashab-al commented on app/interactors/tg/total_vacancies_interactor.rb
> +      category_vacancies_count = vacancies_by_category[category.name] || 0
Мне нужно в модель Vacancy добавить поле category_id с типом foreign_key?

2025-03-02 12:51 UTC, merged