feat: add skooma
Ashab-al/telegram-bot_ashab pull request #5
Opened 2024-11-15 06:43 UTC by Ashab-al

2024-11-15 20:15 UTC, sov-87 commented
надо удалить vendor/cache и добавить в gitignore

2024-11-19 18:47 UTC, sov-87 commented on docs/openapi.yml
> +openapi: 3.1.0
надо добавить описание структуры запроса и ответа

2024-11-19 18:48 UTC, sov-87 commented on spec/controllers/api/vacancy_controller_spec.rb
> +      expect(JSON.parse(response.body)).to eq(vacancies.as_json)
схему и ответ надо проверять в тестах `request`. тест контроллера обычно проверяет только то, что именно контроллер отработал правильно. схема ответа и конкретное содержимое обычно проверяют в тестах на запрос в целом.

2024-11-20 23:06 UTC, Ashab-al commented on docs/openapi.yml
> +openapi: 3.1.0
Поправил

2024-11-21 18:21 UTC, sov-87 requested changes

2024-11-21 18:21 UTC, sov-87 commented on docker-compose.yml
> +      NGROK_AUTHTOKEN: "2j6TAiijPeYxC4602E1IE7ZIo4t_4saB9KzrzpNU9ma8jfi62"
тебя не смущает, что ты свой токен светишь на весь интернет?)

можно использовать переменные среды: https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/

2024-11-21 18:21 UTC, sov-87 commented on spec/controllers/api/vacancy_controller_spec.rb
> +      expect(JSON.parse(response.body)).to eq(vacancies.as_json)
https://rspec.info/features/6-0/rspec-rails/controller-specs/
https://rspec.info/features/6-0/rspec-rails/request-specs/request-spec/

2024-11-21 18:21 UTC, sov-87 commented on docs/openapi.yml
> +                type: object
почему объект, а не массив?

2024-11-21 18:21 UTC, sov-87 commented on docs/openapi.yml
> +                items:
в ответе тоже полезно указывать секцию `required` - это те поля, которые точно будут

2024-11-21 18:21 UTC, sov-87 commented on docs/openapi.yml
> +  "/api/get_all_vacancies":
по описанию сразу можно сказать, что здесь совсем не REST API.

```
get /api/vacancies -> [{id: .., name: ...}, {id: .., name: ...}]
post /api/vacancies -> {id: .., name: ...}
```

получение списка возвращает список, создание - только созданную вакансию.

2024-12-09 21:25 UTC, sov-87 approved these changes

2024-12-13 03:27 UTC, merged